export const professionOptions = [
  'Bar Waitress',
  'Bartender',
  'Butler',
  'Cook',
  'Cook Helper',
  'Cook Italian',
  'Culinary',
  'F&B Services',
  'General Area Cleaner',
  'Housekeeper',
  'Kitchen Service',
  'Room Attendance',
  'Spa Therapis',
  'Steward',
  'Waiter',
  'Waitress',
  'Welcoming Hostess',
].sort((a, b) => a.localeCompare(b));
